### ISSUE TITLE
Ajout de la pagination

### ISSUE THREAD

**Issue by Machou** [adaur/another-private-messaging-system#5]
Salut adaur :)

Peux-tu ajouter la pagination quand on liste les MPs comme pour les topics ?

Épinglée : Blabla [ 1 2 3 4 5 6 7 8 9 ]

Car c'est un peu chiant les MPs à plusieurs page, tu dois cliquer d'abord sur le MP; oui je sais je suis très fainéant :dancers:

**Comment by Karlingue** [comment]
? :D

**Comment by Machou** [comment]
2 ans après, toujours rien ? :P je peux le faire si tu veux :)

**Comment by adaur** [comment]
C'est pas ma priorité là, désolé. Tu peux faire une PR si tu veux.

**Comment by Machou** [comment]
Ok
